import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutWithOptionalHeaderFooter from '../app/components/LayoutWithOptionalHeaderFooter';
import AppLayout from "./components/AppLayout";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Convert layout to client component so we can use usePathname
export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="grammarly:disabled" content="true" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans bg-gray-50 text-gray-900 flex flex-col min-h-screen`}
        suppressHydrationWarning
      >
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
